version: '3.2'
services:
  ruby-on-whales:
    tty: true
    stdin_open: true
    command: sh ./script/start_dev
    environment:
      RAILS_ENV: development
    volumes:
      - '.:/home/app'
    ports:
      - '3000:3000'
    links:
      - 'mailcatcher'
  postgres:
    volumes:
    - type: volume
      source: psql_data
      target: /var/lib/postgresql/data
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
    networks:
      whales_net:
        ipv4_address: 10.5.0.4
volumes:
  psql_data:
