version: '3.2'
services:
  ruby-on-whales:
    image: andrestv/ruby-on-whales:latest
    ports:
      - '3000:3000'
    volumes:
      - type: volume
        source: psql_run_volume
        target: /var/run/postgresql
    depends_on:
      - 'postgres'
    networks:
      whales_net:
        ipv4_address: 10.5.0.2
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - type: volume
        source: psql_run_volume
        target: /var/run/postgresql
      - type: volume
        source: psql_data_volume
        target: /var/lib/postgresql/data
    networks:
      whales_net:
        ipv4_address: 10.5.0.3
volumes:
  psql_run_volume:
  psql_data_volume:

networks:
  whales_net:
    driver: bridge
    ipam:
     config:
      - subnet: 10.5.0.0/16
