default: &default
  adapter: postgresql
  encoding: utf8
  host: 172.18.0.2
  port: 5432
  reconnect: false
  pool: 5

development:
  <<: *default
  database: row_dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: row_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: row_production
  username: postgres
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
