default: &default
  adapter: postgresql
  encoding: utf8
  host: postgres
  reconnect: false
  pool: 5

development:
  <<: *default
  database: row_dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: row_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: kubernetes_poc
  username: postgres
  password: postgres
